#===================================================================================#
# Project information
#===================================================================================#
site_name: Classy Early Access
extra_css:
  - stylesheets/extra.css

#===================================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#===================================================================================#
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo-badge_indigo.png
  favicon: assets/logo-badge_indigo.png
  font:
    text: Mulish, Arial, Helvetica, sans-serif

  features:
    - navigation.top
    - navigation.path
    - navigation.tabs
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - header.autohide
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotaion
    - content.code.copy
    - toc.follow
  palette:
    - scheme: classy
      primary: custom

#===================================================================================#
# Mkdocs Markdown Extentions, Plugins & extras
#===================================================================================#
markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      title: In this article
      toc_depth: 3

plugins:
  - search:
  - redirects:
      redirect_maps:
        "zapier-and-classy.md": "https://support.classy.org/s/article/zapier-and-classy"
        "supporter-center/intro-to-supporter-center.md": "https://support.classy.org/s/article/edit-the-design-of-supporter-accounts"
        "supporter-center/for-supporters.md": "https://support.classy.org/s/article/who-is-classy"

extra:
  analytics:
    provider: google
    property: G-WFNJHCWKWV

#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - Home: index.md
  - Campaign studio:
      - Intro to Campaign Studio: campaign-studio/getting-started/intro-to-campaign-studio.md
      - Designer: campaign-studio/getting-started/intro-to-the-designer.md
      - Emails: campaign-studio/getting-started/email-studio.md
      - Settings: campaign-studio/getting-started/settings.md
      - Frequently asked questions: campaign-studio/getting-started/faq.md
  - Classy Live:
      - Mobile app: classy-live/mobile-app.md
  - Current programs: beta-and-lighthouse/current-programs.md
  - Release notes:
      - Campaign studio: release-notes/campaign-studio.md
