#===================================================================================#
# Project information
#===================================================================================#
site_name: Classy Early Access
extra_css:
  - stylesheets/extra.css

#===================================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#===================================================================================#
theme:
  name: material
  custom_dir: overrides
  logo: docs/assets/ray_white.png
  favicon: docs/assets/favicon-32x32.png
  font:
    text: Mulish, Arial, Helvetica, sans-serif

  features:
    - navigation.top
    - navigation.path
    - navigation.tabs
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - header.autohide
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotaion
    - content.code.copy
    - toc.follow
  palette:
    - scheme: classy
      primary: custom

#===================================================================================#
# Mkdocs Markdown Extentions, Plugins & extras
#===================================================================================#
markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - sane_lists
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      title: In this article
      toc_depth: 3

plugins:
  - search:
  - redirects:
      redirect_maps:
        "zapier-and-classy.md": "https://support.classy.org/s/article/zapier-and-classy"
        "supporter-center/intro-to-supporter-center.md": "https://support.classy.org/s/article/edit-the-design-of-supporter-accounts"
        "supporter-center/for-supporters.md": "https://support.classy.org/s/article/who-is-classy"
        "chariot-and-classy.md": "chariot/chariot-and-classy.md"
        "campaign-studio/getting-started/intro-to-campaign-studio.md": "https://support.classy.org/s/article/intro-to-classy-studio"
        "campaign-studio/getting-started/settings.md": "https://support.classy.org/s/article/intro-to-classy-studio"
        "campaign-studio/getting-started/faq.md": "https://support.classy.org/s/article/intro-to-classy-studio"
        "campaign-studio/getting-started/intro-to-the-designer.md": "https://support.classy.org/s/article/classy-studio-designer"
        "campaign-studio/getting-started/email-studio.md": "https://support.classy.org/s/article/email-studio"
        "domain-masking.md": "https://support.classy.org/s/article/how-to-set-up-domain-masking"
        "classy-for-salesforce-fundraising.md": "https://support.classy.org/s/article/install-classy-for-salesforce-fundraising"
        "classy-live/bulk-close.md": "https://support.classy.org/s/article/bulk-close-balances-in-classy-live"
        "giving-cart.md": "https://support.classy.org/s/article/giving-cart"
        "classy-live/card-tokenization.md": "https://support.classy.org/s/article/credit-card-tokenization"

extra:
  analytics:
    provider: google
    property: G-NC9WXEJ9N3

#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - Home: index.md
  - Classy Live:
      - Mobile app: classy-live/mobile-app.md
      - Reader M2: classy-live/reader-m2.md
      - Import attendees: classy-live/import-attendees.md
      - Donor covered fees: classy-live/donor-covered-fees.md
      - Group registration: classy-live/group-registration.md
  - Multifactor authentication: multifactor-authentication.md
  - Campaign insights: campaign-insights.md
  - Current programs: beta-and-lighthouse/current-programs.md
